# -*- mode: python ; coding: utf-8 -*-

block_cipher = None
binaries = []
datas = [
    ("C:\\Program Files\\Tesseract-OCR\\tesseract.exe", "tesseract"),
    ("C:\\Program Files\\Tesseract-OCR\\libarchive-13.dll", "tesseract"),
    ("C:\\Program Files\\Tesseract-OCR\\libb2-1.dll", "tesseract"),
    ("C:\\Program Files\\Tesseract-OCR\\libbrotlicommon.dll", "tesseract"),
    ("C:\\Program Files\\Tesseract-OCR\\libbrotlidec.dll", "tesseract"),
    ("C:\\Program Files\\Tesseract-OCR\\libbz2-1.dll", "tesseract"),
    ("C:\\Program Files\\Tesseract-OCR\\libcairo-2.dll", "tesseract"),
    ("C:\\Program Files\\Tesseract-OCR\\libcrypto-3-x64.dll", "tesseract"),
    ("C:\\Program Files\\Tesseract-OCR\\libcurl-4.dll", "tesseract"),
    ("C:\\Program Files\\Tesseract-OCR\\libdatrie-1.dll", "tesseract"),
    ("C:\\Program Files\\Tesseract-OCR\\libdeflate.dll", "tesseract"),
    ("C:\\Program Files\\Tesseract-OCR\\libexpat-1.dll", "tesseract"),
    ("C:\\Program Files\\Tesseract-OCR\\libffi-8.dll", "tesseract"),
    ("C:\\Program Files\\Tesseract-OCR\\libfontconfig-1.dll", "tesseract"),
    ("C:\\Program Files\\Tesseract-OCR\\libfreetype-6.dll", "tesseract"),
    ("C:\\Program Files\\Tesseract-OCR\\libfribidi-0.dll", "tesseract"),
    ("C:\\Program Files\\Tesseract-OCR\\libgcc_s_seh-1.dll", "tesseract"),
    ("C:\\Program Files\\Tesseract-OCR\\libgif-7.dll", "tesseract"),
    ("C:\\Program Files\\Tesseract-OCR\\libgio-2.0-0.dll", "tesseract"),
    ("C:\\Program Files\\Tesseract-OCR\\libglib-2.0-0.dll", "tesseract"),
    ("C:\\Program Files\\Tesseract-OCR\\libgmodule-2.0-0.dll", "tesseract"),
    ("C:\\Program Files\\Tesseract-OCR\\libgobject-2.0-0.dll", "tesseract"),
    ("C:\\Program Files\\Tesseract-OCR\\libgraphite2.dll", "tesseract"),
    ("C:\\Program Files\\Tesseract-OCR\\libharfbuzz-0.dll", "tesseract"),
    ("C:\\Program Files\\Tesseract-OCR\\libiconv-2.dll", "tesseract"),
    ("C:\\Program Files\\Tesseract-OCR\\libicudt72.dll", "tesseract"),
    ("C:\\Program Files\\Tesseract-OCR\\libicuin72.dll", "tesseract"),
    ("C:\\Program Files\\Tesseract-OCR\\libicuuc72.dll", "tesseract"),
    ("C:\\Program Files\\Tesseract-OCR\\libidn2-0.dll", "tesseract"),
    ("C:\\Program Files\\Tesseract-OCR\\libintl-8.dll", "tesseract"),
    ("C:\\Program Files\\Tesseract-OCR\\libjbig-0.dll", "tesseract"),
    ("C:\\Program Files\\Tesseract-OCR\\libjpeg-8.dll", "tesseract"),
    ("C:\\Program Files\\Tesseract-OCR\\libleptonica-6.dll", "tesseract"),
    ("C:\\Program Files\\Tesseract-OCR\\libLerc.dll", "tesseract"),
    ("C:\\Program Files\\Tesseract-OCR\\liblz4.dll", "tesseract"),
    ("C:\\Program Files\\Tesseract-OCR\\liblzma-5.dll", "tesseract"),
    ("C:\\Program Files\\Tesseract-OCR\\libopenjp2-7.dll", "tesseract"),
    ("C:\\Program Files\\Tesseract-OCR\\libpango-1.0-0.dll", "tesseract"),
    ("C:\\Program Files\\Tesseract-OCR\\libpangocairo-1.0-0.dll", "tesseract"),
    ("C:\\Program Files\\Tesseract-OCR\\libpangoft2-1.0-0.dll", "tesseract"),
    ("C:\\Program Files\\Tesseract-OCR\\libpangowin32-1.0-0.dll", "tesseract"),
    ("C:\\Program Files\\Tesseract-OCR\\libpcre2-8-0.dll", "tesseract"),
    ("C:\\Program Files\\Tesseract-OCR\\libpixman-1-0.dll", "tesseract"),
    ("C:\\Program Files\\Tesseract-OCR\\libpng16-16.dll", "tesseract"),
    ("C:\\Program Files\\Tesseract-OCR\\libpsl-5.dll", "tesseract"),
    ("C:\\Program Files\\Tesseract-OCR\\libsharpyuv-0.dll", "tesseract"),
    ("C:\\Program Files\\Tesseract-OCR\\libssh2-1.dll", "tesseract"),
    ("C:\\Program Files\\Tesseract-OCR\\libstdc++-6.dll", "tesseract"),
    ("C:\\Program Files\\Tesseract-OCR\\libtesseract-5.dll", "tesseract"),
    ("C:\\Program Files\\Tesseract-OCR\\libthai-0.dll", "tesseract"),
    ("C:\\Program Files\\Tesseract-OCR\\libtiff-6.dll", "tesseract"),
    ("C:\\Program Files\\Tesseract-OCR\\libunistring-5.dll", "tesseract"),
    ("C:\\Program Files\\Tesseract-OCR\\libwebp-7.dll", "tesseract"),
    ("C:\\Program Files\\Tesseract-OCR\\libwebpmux-3.dll", "tesseract"),
    ("C:\\Program Files\\Tesseract-OCR\\libwinpthread-1.dll", "tesseract"),
    ("C:\\Program Files\\Tesseract-OCR\\libzstd.dll", "tesseract"),
    ("C:\\Program Files\\Tesseract-OCR\\zlib1.dll", "tesseract"),

    ("C:\Program Files\Tesseract-OCR\\tessdata\eng.traineddata", "data\\tessdata"),
    ("C:\Program Files\Tesseract-OCR\\tessdata\jav.traineddata", "data\\tessdata"),
    ("C:\Program Files\Tesseract-OCR\\tessdata\jpn.traineddata", "data\\tessdata"),
    ("C:\Program Files\Tesseract-OCR\\tessdata\jpn_vert.traineddata", "data\\tessdata"),
    ("C:\Program Files\Tesseract-OCR\\tessdata\osd.traineddata", "data\\tessdata"),
    
    ("C:\Program Files\poppler\Library\\bin\cairo.dll", "popper"),
    ("C:\Program Files\poppler\Library\\bin\charset.dll", "popper"),
    ("C:\Program Files\poppler\Library\\bin\deflate.dll", "popper"),
    ("C:\Program Files\poppler\Library\\bin\expat.dll", "popper"),
    ("C:\Program Files\poppler\Library\\bin\\fontconfig-1.dll", "popper"),
    ("C:\Program Files\poppler\Library\\bin\\freetype.dll", "popper"),
    ("C:\Program Files\poppler\Library\\bin\\iconv.dll", "popper"),
    ("C:\Program Files\poppler\Library\\bin\\jpeg8.dll", "popper"),
    ("C:\Program Files\poppler\Library\\bin\\lcms2.dll", "popper"),
    ("C:\Program Files\poppler\Library\\bin\\Lerc.dll", "popper"),
    ("C:\Program Files\poppler\Library\\bin\\libcrypto-3-x64.dll", "popper"),
    ("C:\Program Files\poppler\Library\\bin\\libcurl.dll", "popper"),
    ("C:\Program Files\poppler\Library\\bin\\libexpat.dll", "popper"),
    ("C:\Program Files\poppler\Library\\bin\\liblzma.dll", "popper"),
    ("C:\Program Files\poppler\Library\\bin\\libpng16.dll", "popper"),
    ("C:\Program Files\poppler\Library\\bin\\libssh2.dll", "popper"),
    ("C:\Program Files\poppler\Library\\bin\\libtiff.dll", "popper"),
    ("C:\Program Files\poppler\Library\\bin\\libzstd.dll", "popper"),
    ("C:\Program Files\poppler\Library\\bin\\openjp2.dll", "popper"),
    ("C:\Program Files\poppler\Library\\bin\\pdfattach.exe", "popper"),
    ("C:\Program Files\poppler\Library\\bin\\pdfdetach.exe", "popper"),
    ("C:\Program Files\poppler\Library\\bin\pdffonts.exe", "popper"),
    ("C:\Program Files\poppler\Library\\bin\pdfimages.exe", "popper"),
    ("C:\Program Files\poppler\Library\\bin\pdfinfo.exe", "popper"),
    ("C:\Program Files\poppler\Library\\bin\pdfseparate.exe", "popper"),
    ("C:\Program Files\poppler\Library\\bin\pdftocairo.exe", "popper"),
    ("C:\Program Files\poppler\Library\\bin\pdftohtml.exe", "popper"),
    ("C:\Program Files\poppler\Library\\bin\pdftoppm.exe", "popper"),
    ("C:\Program Files\poppler\Library\\bin\pdftops.exe", "popper"),
    ("C:\Program Files\poppler\Library\\bin\pdftotext.exe", "popper"),
    ("C:\Program Files\poppler\Library\\bin\pdfunite.exe", "popper"),
    ("C:\Program Files\poppler\Library\\bin\poppler.dll", "popper"),
    ("C:\Program Files\poppler\Library\\bin\poppler-cpp.dll", "popper"),
    ("C:\Program Files\poppler\Library\\bin\poppler-glib.dll", "popper"),
    ("C:\Program Files\poppler\Library\\bin\\tiff.dll", "popper"),
    ("C:\Program Files\poppler\Library\\bin\zlib.dll", "popper"),
    ("C:\Program Files\poppler\Library\\bin\zstd.dll", "popper"),
    ("C:\Program Files\poppler\Library\\bin\zstd.exe", "popper"),
]

a = Analysis(
    ["main.py"],
    pathex=[],
    binaries=binaries,
    datas=datas,
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name="pdf-shiwake",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=["pdf-shiwake.ico"],
)
